apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-mme-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-mme
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-mme
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/open5gs:v2.1.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "./bin/open5gs-mmed"]
        volumeMounts:
        - name: open5gs-mmecfg
          mountPath: /open5gs/install/etc/open5gs/mme.yaml
          subPath: mme.yaml
        - name: open5gs-freediameter-mmecfg
          mountPath: /open5gs/install/etc/freeDiameter/mme.conf
          subPath: mme.conf
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br1", "-n=eth1", "-i=192.168.2.4/24", "-g=192.168.2.254"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: open5gs-mmecfg
        configMap:
          name: open5gs-configmap
          items: 
          - key: mme.yaml
            path: mme.yaml
      - name: open5gs-freediameter-mmecfg
        configMap:
          name: open5gs-freediameter-configmap
          items: 
          - key: mme.conf
            path: mme.conf
